SadenaFenix/Controllers/Georeferenciacion/GeoOficialiasController.cs
using Newtonsoft.Json;
using SadenaFenix.Models.Catalogos.Geografia;
using SadenaFenix.Models.Georeferenciacion;
using SadenaFenix.Services;
using SadenaFenix.Services.Georeferenciacion;
using SadenaFenix.Transport.Catalogos;
using SadenaFenix.Transport.Georeferenciacion;
using SadenaFenix.Transport.Usuarios.Acceso;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services;

namespace SadenaFenix.Controllers.Georeferenciacion
{
    public class GeoOficialiasController : Controller
    {
        // GET: GeoOficialias/OficialiasTabla
        [HttpGet]
        public ActionResult OficialiasTabla()
        {
            ConsultaOficialiasPeticion peticion = new ConsultaOficialiasPeticion
            {
                ColMunicipios = new Collection<Municipio>()
            };
            ConsultaOficialiasRespuesta respuesta = new GeoServicio().ConsultarOficialias(peticion);
            if(respuesta.Cabecero.EsRespuestaExistosa())
            {
                return View(respuesta.DTOficialia);
            }
            else
            {
                return View(new DataTable());
            }           
        }


        [HttpGet]
        public ActionResult CrearOficialia()
        {
            CabeceroPeticion cabeceroPeticion = new CabeceroPeticion
            {
                SesionId = 1
            };
            Servicio servicio = new Servicio();

            Oficialia oficialia = new Oficialia();
            CatalogoMunicipioRespuesta catalogoMunicipioRespuesta = servicio.ConsultarCatalogoMunicipioGeografia(cabeceroPeticion);
            oficialia.MunicipioLista = new List<Municipio>(catalogoMunicipioRespuesta.ColMunicipio);


            CatalogoLocalidadRespuesta catalogoLocalidadRespuesta = servicio.ConsultarCatalogoLocalidadGeografiaCoahuila(cabeceroPeticion);                       
            oficialia.LocalidadLista = new List<Localidad>(catalogoLocalidadRespuesta.ColLocalidad);
            return View(oficialia);
        }

        [WebMethod]
        public ActionResult GuardarOficialia(string jsonOficialia)
        {
            InsertarOficialiaPeticion peticion = new InsertarOficialiaPeticion
            {
                Oficialia = JsonConvert.DeserializeObject<Oficialia>(jsonOficialia)
            };

            GeoServicio geoServicio = new GeoServicio();
            InsertarOficialiaRespuesta respuesta = geoServicio.InsertarOficialia(peticion);
            return Json(respuesta, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult ActualizarOficialia(int id)
        {
            CabeceroPeticion cabeceroPeticion = new CabeceroPeticion
            {
                SesionId = 1
            };

            ConsultaOficialiaPeticion peticion = new ConsultaOficialiaPeticion
            {
                OId = id
            };

            GeoServicio geoServicio = new GeoServicio();
            ConsultaOficialiaRespuesta respuesta = geoServicio.ConsultarOficialia(peticion);
            Oficialia oficialia = respuesta.Oficialia;

            Servicio servicio = new Servicio();
            CatalogoMunicipioRespuesta catalogoMunicipioRespuesta = servicio.ConsultarCatalogoMunicipioGeografia(cabeceroPeticion);
            oficialia.MunicipioLista = new List<Municipio>(catalogoMunicipioRespuesta.ColMunicipio);

            CatalogoLocalidadRespuesta catalogoLocalidadRespuesta = servicio.ConsultarCatalogoLocalidadGeografiaCoahuila(cabeceroPeticion);
            oficialia.LocalidadLista = new List<Localidad>(catalogoLocalidadRespuesta.ColLocalidad);
            return View(oficialia);
        }

        [WebMethod]
        public ActionResult ActualizarOficialia(string jsonOficialia)
        {
            ActualizarOficialiaPeticion peticion = new ActualizarOficialiaPeticion
            {
                Oficialia = JsonConvert.DeserializeObject<Oficialia>(jsonOficialia)
            };

            GeoServicio geoServicio = new GeoServicio();
            ActualizarOficialiaRespuesta respuesta = geoServicio.ActualizarOficialia(peticion);
            return Json(respuesta, JsonRequestBehavior.AllowGet);
        }

        [WebMethod]
        public ActionResult EliminarOficialia(int oid)
        {
            
            GeoServicio geoServicio = new GeoServicio();
            ActualizarOficialiaRespuesta respuesta = geoServicio.EliminarOficialia(oid);
            return Json(respuesta, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ObtenerLocalidadesPorMunicipio()
        {
            
            return PartialView("");
        }

        // POST: GeoOficialias/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: GeoOficialias/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: GeoOficialias/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: GeoOficialias/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: GeoOficialias/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SadenaFenix/Views/GeoOficialias/ActualizarOficialia.cshtml
@model SadenaFenix.Models.Georeferenciacion.Oficialia
@{
    Layout = "~/Views/Shared/_GeoLayout.cshtml";
    ViewData["Root"] = "Sadena";
    ViewData["Modulo"] = "Georeferenciación";
    ViewData["Option"] = "Localias";
    ViewData["TableName"] = "Actualizar Oficialía";
    ViewData["Title"] = ViewData["Modulo"] + " / " + ViewData["Option"];
}
@section Scripts
{
    <script src="@Url.Content("~/Scripts/js/georefenciacion/georeferenciacion.js")"></script>
    <script src="@Url.Content("~/Scripts/js/utilerias/mapas.js")"></script>
    <!-- Replace the value of the key parameter with your own API key. -->
    <script src="@Url.Content("https://maps.googleapis.com/maps/api/js?key=" + ViewBag.ApiKey + "&libraries=places&callback=initMap")" async defer></script>
}


<!-- Page content -->
<div class="page-content">

    <!-- Container -->
    <div class="container">

        <!-- Breadcrumb -->
        <section class="pull-right">
            <ul class="breadcrumb">
                <li><a asp-area="" asp-controller="Home" asp-action="Index"><i class="fa fa-home mr-3"></i>@ViewData["Root"]</a></li>
                <li><a href="#">@ViewData["Modulo"]</a></li>
                <li class="active">@ViewData["Option"]</li>
            </ul>
        </section>
        <!-- ./breadcrumb -->

        <section>
            <div class="row">
                <div class="col-sm-12">
                    <div class="well loading-well">
                        
                        <fieldset>
                            <legend>@ViewData["TableName"]</legend>

                            <div class="form-horizontal">

                                <hr />

                                @Html.HiddenFor(model => model.OId)

                                <div class="form-group">
                                    @Html.LabelFor(model => model.OficialiaId, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.OficialiaId, new { htmlAttributes = new { @class = "form-control ValidacionNumero", @maxlength = "10" } })
                                        @Html.ValidationMessageFor(model => model.OficialiaId, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.MpioDesc, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.MpioDesc, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" , @identificador = Model.MpioId } })
                                        @Html.DropDownListFor(model => model.MpioId, new SelectList(Model.MunicipioLista, "MpioId", "MpioDesc"), new { id = "MunicipioLista", @class = "selectMpio show-tick form-control hiddElement" })
                                        @Html.ValidationMessageFor(model => model.MpioDesc, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.LocDesc, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.LocDesc, new { htmlAttributes = new {@class = "form-control", @readonly = "readonly" , @identificador = Model.LocId } })
                                        @Html.DropDownListFor(model => model.LocId, new SelectList(Model.LocalidadLista, "LocId", "LocDesc", "LocMpioId", "LocMpioDesc", "", ""), new { id = "LocalidadLista", @class = "selectLoc show-tick form-control hiddElement" })
                                        @Html.ValidationMessageFor(model => model.LocDesc, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Calle, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Calle, new { htmlAttributes = new { @class = "form-control ValidacionTexto", @maxlength = "60" } })
                                        @Html.ValidationMessageFor(model => model.Calle, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Numero, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Numero, new { htmlAttributes = new { @class = "form-control ValidacionTexto", @maxlength = "10" } })
                                        @Html.ValidationMessageFor(model => model.Numero, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Colonia, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Colonia, new { htmlAttributes = new { @class = "form-control ValidacionTexto", @maxlength = "60" } })
                                        @Html.ValidationMessageFor(model => model.Colonia, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.CP, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.CP, new { htmlAttributes = new { @class = "form-control ValidacionNumero", @maxlength = "5" } })
                                        @Html.ValidationMessageFor(model => model.CP, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control ValidacionTelefono", @maxlength = "13" } })
                                        @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Nombres, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Nombres, new { htmlAttributes = new { @class = "form-control ValidacionTexto", @maxlength = "80" } })
                                        @Html.ValidationMessageFor(model => model.Nombres, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Apellidos, new { htmlAttributes = new { @class = "form-control ValidacionTexto", @maxlength = "80" } })
                                        @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.CorreoE, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.CorreoE, new { htmlAttributes = new { @class = "form-control", @maxlength = "60" } })
                                        @Html.ValidationMessageFor(model => model.CorreoE, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Latitud, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Latitud, new { htmlAttributes = new { @class = "form-control", @maxlength = "20" } })
                                        @Html.ValidationMessageFor(model => model.Latitud, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Longitud, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Longitud, new { htmlAttributes = new { @class = "form-control", @maxlength = "20" } })
                                        @Html.ValidationMessageFor(model => model.Longitud, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Observaciones, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Observaciones, new { htmlAttributes = new { @class = "form-control ValidacionTexto", @maxlength = "255" } })
                                        @Html.ValidationMessageFor(model => model.Observaciones, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input id="BotonActualizarOficialia" type="submit" value="Actualizar" class="btn btn-default" />
                                        <input id="BotonEliminarOficialia" type="submit" value="Eliminar" class="btn btn-default" />
                                    </div>                                   
                                </div>
                            </div>

                            <a href="@Url.Action("OficialiasTabla","GeoOficialias")">Ir a Consulta Oficialias</a>
                        </fieldset>
                       
                    </div>
                </div>
            </div>

        </section>

    </div>
    <!-- ./container -->
    <!-- Container -->
    <div class="container">

        <section>

            <div style="display: none">
                <input id="inputUbicacionMapa"
                       class="controls"
                       type="text"
                       placeholder="Introduce la ubicación">
            </div>

            <div id="infowindow-content">
                <img src="" width="16" height="16" id="place-icon">
                <span id="place-name" class="title"></span><br>
                <span id="place-address"></span>
            </div>


            <div id="mapGoogle" class="z-depth-1-half map-container" style="height: 500px">
                <iframe src="https://maps.google.com/maps?q=manhatan&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0"
                        style="border:0" allowfullscreen></iframe>
            </div>
        </section>

    </div>
    <!-- ./container -->
</div>
<!-- ./page content -->

SadenaFenix/Views/GeoOficialias/CrearOficialia.cshtml
@model SadenaFenix.Models.Georeferenciacion.Oficialia
@{
    Layout = "~/Views/Shared/_GeoLayout.cshtml";
    ViewData["Root"] = "Sadena";
    ViewData["Modulo"] = "Georeferenciación";
    ViewData["Option"] = "Localias";
    ViewData["TableName"] = "Crear Oficialía";
    ViewData["Title"] = ViewData["Modulo"] + " / " + ViewData["Option"];
}
@section Scripts
{
    <script src="@Url.Content("~/Scripts/js/georefenciacion/georeferenciacion.js")"></script>
    <script src="@Url.Content("~/Scripts/js/utilerias/mapas.js")"></script>
    <!-- Replace the value of the key parameter with your own API key. -->
    <script src="@Url.Content("https://maps.googleapis.com/maps/api/js?key=" + ViewBag.ApiKey + "&libraries=places&callback=initMap")" async defer></script>

}


<!-- Page content -->
<div class="page-content">

    <!-- Container -->
    <div class="container">

        <!-- Breadcrumb -->
        <section class="pull-right">
            <ul class="breadcrumb">
                <li><a asp-area="" asp-controller="Home" asp-action="Index"><i class="fa fa-home mr-3"></i>@ViewData["Root"]</a></li>
                <li><a href="#">@ViewData["Modulo"]</a></li>
                <li class="active">@ViewData["Option"]</li>
            </ul>
        </section>
        <!-- ./breadcrumb -->

        <section>
            <div class="row">
                <div class="col-sm-12">
                    <div class="well loading-well">
                        <!-- Form -->
                        @*<form class="form-horizontal">*@
                        <fieldset>
                            <legend>@ViewData["TableName"]</legend>

                            <div class="form-horizontal">

                                <hr />

                                <div class="form-group">
                                    @Html.LabelFor(model => model.OficialiaId, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.OficialiaId, new { htmlAttributes = new { @class = "form-control ValidacionNumero", @maxlength = "10" } })
                                        @Html.ValidationMessageFor(model => model.OficialiaId, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.MpioDesc, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.DropDownListFor(model => model.MpioId, new SelectList(Model.MunicipioLista, "MpioId", "MpioDesc"), new { id = "MunicipioLista", @class = "selectMpio show-tick form-control" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.LocDesc, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.DropDownListFor(model => model.LocDesc, new SelectList(Model.LocalidadLista, "LocId", "LocDesc", "LocMpioId", "LocMpioDesc", "", ""), new { id = "LocalidadLista", @class = "selectLoc show-tick form-control" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Calle, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Calle, new { htmlAttributes = new { @class = "form-control ValidacionTexto", @maxlength = "60" } })
                                        @Html.ValidationMessageFor(model => model.Calle, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Numero, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Numero, new { htmlAttributes = new { @class = "form-control ValidacionTexto", @maxlength = "10" } })
                                        @Html.ValidationMessageFor(model => model.Numero, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Colonia, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Colonia, new { htmlAttributes = new { @class = "form-control ValidacionTexto", @maxlength = "60" } })
                                        @Html.ValidationMessageFor(model => model.Colonia, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.CP, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.CP, new { htmlAttributes = new { @class = "form-control ValidacionNumero", @maxlength = "5" } })
                                        @Html.ValidationMessageFor(model => model.CP, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control ValidacionTelefono", @maxlength = "13" } })
                                        @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Nombres, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Nombres, new { htmlAttributes = new { @class = "form-control ValidacionTexto", @maxlength = "80" } })
                                        @Html.ValidationMessageFor(model => model.Nombres, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Apellidos, new { htmlAttributes = new { @class = "form-control ValidacionTexto", @maxlength = "80" } })
                                        @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.CorreoE, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.CorreoE, new { htmlAttributes = new { @class = "form-control", @maxlength = "60" } })
                                        @Html.ValidationMessageFor(model => model.CorreoE, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Latitud, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Latitud, new { htmlAttributes = new { @class = "form-control", @maxlength = "20" } })
                                        @Html.ValidationMessageFor(model => model.Latitud, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Longitud, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Longitud, new { htmlAttributes = new { @class = "form-control", @maxlength = "20" } })
                                        @Html.ValidationMessageFor(model => model.Longitud, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Observaciones, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Observaciones, new { htmlAttributes = new { @class = "form-control ValidacionTexto", @maxlength = "255" } })
                                        @Html.ValidationMessageFor(model => model.Observaciones, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input id="BotonCrearOficialia" type="submit" value="Crear" class="btn btn-default" />
                                    </div>
                                </div>
                            </div>

                            <a href="@Url.Action("OficialiasTabla","GeoOficialias")">Ir a Consulta Oficialias</a>                            
                        </fieldset>
                        @*</form>*@
                        <!-- ./form -->
                    </div>
                </div>
            </div>

        </section>

    </div>
    <!-- ./container -->
    <!-- Container -->
    <div class="container">

        <section>

            <div style="display: none">
                <input id="inputUbicacionMapa"
                       class="controls"
                       type="text"
                       placeholder="Introduce la ubicación">
            </div>

            @*<div id="infowindow-content">
                <span id="place-name" class="title"></span><br>
                <strong>Place ID:</strong> <span id="place-id"></span><br>
                <span id="place-address"></span>
            </div>*@

            <div id="infowindow-content">
                <img src="" width="16" height="16" id="place-icon">
                <span id="place-name" class="title"></span><br>
                <span id="place-address"></span>
            </div>


            <div id="mapGoogle" class="z-depth-1-half map-container" style="height: 500px">
                <iframe src="https://maps.google.com/maps?q=manhatan&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0"
                        style="border:0" allowfullscreen></iframe>
            </div>
        </section>

    </div>
    <!-- ./container -->
</div>
<!-- ./page content -->